# Generated by Django 4.2.17 on 2024-12-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('prep', models.CharField(blank=True, max_length=254, null=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trans_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cholestorol', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fibre', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vitimin_a', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vitimin_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('caffeine', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
