# Generated by Django 4.2.17 on 2024-12-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_rename_cholestorol_stat_cholesterol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('store_id', models.CharField(blank=True, max_length=254, null=True)),
                ('store_location', models.CharField(blank=True, max_length=254, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('product_category', models.CharField(blank=True, max_length=254, null=True)),
                ('product_type', models.CharField(blank=True, max_length=254, null=True)),
                ('product_detail', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
