# Generated by Django 4.2.17 on 2024-12-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeequality',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='coffeequality',
            name='year_of_harvest',
        ),
        migrations.AddField(
            model_name='coffeequality',
            name='country',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='coffeequality',
            name='year',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='acidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='aftertaste',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='aroma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='body',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='colour',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='flavour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='moisture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='processing_method',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='species',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='sweetness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='unifirmity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='coffeequality',
            name='variety',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
