# Generated by Django 4.2.17 on 2024-12-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_remove_coffeequality_country_of_origin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeequality',
            old_name='unifirmity',
            new_name='uniformity',
        ),
    ]
